import os
import pandas as pd
from agents.orchestrator import FlightGuardOrchestrator
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def generate_pdf_report(audit_df):
    os.makedirs("output", exist_ok=True)
    pdf_path = "output/flightguard_audit_report.pdf"
    
    # Page setup with proper margins (letter width = 612 pt)
    doc = SimpleDocTemplate(
        pdf_path, 
        pagesize=letter, 
        rightMargin=36, 
        leftMargin=36, 
        topMargin=40, 
        bottomMargin=40
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles to maintain hierarchy and prevent any collision
    title_style = ParagraphStyle(
        'DocTitle', 
        parent=styles['Heading1'], 
        fontSize=16, 
        textColor=colors.HexColor('#0f172a'), 
        spaceAfter=4, 
        alignment=0
    )
    subtitle_style = ParagraphStyle(
        'DocSub', 
        parent=styles['Normal'], 
        fontSize=10, 
        textColor=colors.HexColor('#475569'), 
        spaceAfter=15
    )
    section_style = ParagraphStyle(
        'SectionHead', 
        parent=styles['Heading2'], 
        fontSize=12, 
        textColor=colors.HexColor('#1e293b'), 
        spaceBefore=10, 
        spaceAfter=8
    )
    body_style = ParagraphStyle(
        'BodyTextCustom', 
        parent=styles['Normal'], 
        fontSize=9, 
        leading=13, 
        textColor=colors.HexColor('#475569'), 
        spaceAfter=15
    )
    
    # Table Cell Paragraph Styles (Crucial for text wrapping & zero overlap)
    cell_style = ParagraphStyle(
        'TableCell', 
        parent=styles['Normal'], 
        fontSize=7.5, 
        leading=10, 
        textColor=colors.HexColor('#334155')
    )
    cell_header_style = ParagraphStyle(
        'TableHeader', 
        parent=styles['Normal'], 
        fontSize=7.5, 
        leading=10, 
        fontName='Helvetica-Bold',
        textColor=colors.whitesmoke
    )

    elements = [
        Paragraph("FlightGuard Autonomous Systems", title_style),
        Paragraph("Mission-Critical Aerospace Telemetry, RUL Forecasting & Explainable AI Audit Report", subtitle_style),
        Spacer(1, 5),
        Paragraph("Executive Summary & Operational Overview", section_style),
        Paragraph(
            "This automated compliance and telemetry audit report is generated by the FlightGuard Multi-Agent Swarm "
            "integrated with Tabular Stacking Ensembles, Remaining Useful Life (RUL) regression forecasting, "
            "and Explainable AI (XAI) feature attribution modules. The findings below detail real-time sensor anomaly detections, "
            "computed failure risks, estimated operational lifespans, and natural-language engineering justifications "
            "to ensure zero black-box risk in safety-critical flight maintenance operations.",
            body_style
        ),
        Paragraph("Comprehensive Fleet Audit Log, RUL Windows & XAI Adjudication", section_style)
    ]
    
    # Building table headers using Paragraphs (Updated with RUL & Maintenance Window columns)
    table_data = [[
        Paragraph("Tail Number", cell_header_style),
        Paragraph("Hours", cell_header_style),
        Paragraph("Sensor Status", cell_header_style),
        Paragraph("Risk", cell_header_style),
        Paragraph("Est. RUL", cell_header_style),
        Paragraph("Maintenance Directive", cell_header_style),
        Paragraph("XAI Engineering Justification", cell_header_style)
    ]]
    
    # Processing 60 rows to span across pages smoothly with automatic page breaks
    for _, row in audit_df.head(60).iterrows():
        table_data.append([
            Paragraph(str(row["Tail Number"]), cell_style),
            Paragraph(str(row["Operating Hours"]), cell_style),
            Paragraph(str(row["Sensor Status"]), cell_style),
            Paragraph(str(row["Risk Score"]), cell_style),
            Paragraph(str(row["Estimated RUL (Hrs)"]), cell_style),
            Paragraph(str(row["Maintenance Directive"]), cell_style),
            Paragraph(str(row["XAI Justification"]), cell_style)
        ])
        
    # Explicit column widths totaling ~540 points (fits perfectly inside letter width minus margins)
    col_widths = [65, 38, 90, 32, 45, 90, 180]
    
    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#ffffff'), colors.HexColor('#f8fafc')]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    
    elements.append(t)
    doc.build(elements)
    print(f"-> Success: Multi-page professional PDF Audit Report generated at {pdf_path}")

def main():
    print("--- Initializing FlightGuard Autonomous Swarm Pipeline ---")
    orchestrator = FlightGuardOrchestrator()
    audit_df = orchestrator.execute_swarm_pipeline()
    generate_pdf_report(audit_df)
    print("--- FlightGuard Execution Completed Successfully! ---")

if __name__ == "__main__":
    main()